# Generated by Django 4.0.4 on 2022-05-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='name',
            field=models.CharField(default='My Classroom', max_length=20),
            preserve_default=False,
        ),
    ]
