# Generated by Django 4.0.4 on 2022-05-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_classroom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_id',
            field=models.CharField(max_length=10),
        ),
    ]
