# Generated by Django 4.0.4 on 2022-05-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_student_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='personality',
            field=models.IntegerField(null=True),
        ),
    ]
