# Generated by Django 4.0.4 on 2022-05-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_classroom_partnership_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnership_id', models.CharField(max_length=10, null=True, unique=True)),
                ('session_id', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
