# Generated by Django 4.0.4 on 2022-06-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_classroom_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='first',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='first',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(default='My Classroom', max_length=100),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='owner',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
