# Generated by Django 4.0.4 on 2022-06-10 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_classroom_first_student_first_alter_classroom_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
