# Generated by Django 4.0.4 on 2022-06-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_session_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='class_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
