# Generated by Django 4.0.4 on 2022-06-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_session_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='class_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
