# Generated by Django 4.0.4 on 2022-06-11 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_session_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 11, 0, 46, 3, 747381)),
        ),
    ]
