# Generated by Django 4.0.4 on 2022-06-12 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_session_expires_alter_session_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.IntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='session',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 12, 18, 14, 55, 558438)),
        ),
    ]
