# Generated by Django 4.0.4 on 2022-06-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_student_image_alter_session_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expires',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.IntegerField(default=0),
        ),
    ]
