# Generated by Django 4.0.4 on 2022-06-12 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_session_expires_alter_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
