# Generated by Django 4.0.4 on 2022-06-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.IntegerField(default=18),
        ),
    ]
