# Generated by Django 4.0.4 on 2022-06-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_student_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(default='', max_length=1500)),
                ('week', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='num_calls',
            field=models.IntegerField(default=0),
        ),
    ]
