# Generated by Django 4.0.4 on 2022-06-18 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_questions_classroom_num_calls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='week',
            new_name='num',
        ),
    ]
