# Generated by Django 4.0.4 on 2022-06-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_week_questions_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
