# Generated by Django 4.0.4 on 2022-06-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_classroom_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='is_subscribed',
        ),
        migrations.AddField(
            model_name='classroom',
            name='expires',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
