# Generated by Django 4.0.4 on 2022-07-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_classroom_is_subscribed_classroom_expires'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=1500)),
                ('num', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
