# Generated by Django 4.0.4 on 2022-09-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_questions_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='num',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='questions',
            field=models.CharField(default='', max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='url',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
