# Generated by Django 4.0.4 on 2022-09-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_questions_name_alter_questions_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='questions',
            name='num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questions',
            name='questions',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='url',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
